#! /bin/bash

export VERSION="43-2"
export SYSTEM_DESC="KhimeraOS"
export SYSTEM_NAME="khimeraos"
export USERNAME="gamer"
export SIZE="10000MB"
export ARCHIVE_DATE=$(date -d 'yesterday' +%Y/%m/%d)
export WEBSITE="https://chimeraos.org"
export DOCUMENTATION_URL="https://chimeraos.org/about"
export BUG_REPORT_URL="https://github.com/elril0000/khimeraos/issues"

export KERNEL_PACKAGE="linux-chimeraos"
export KERNEL_PACKAGE_ORIGIN="local"

export PACKAGES="\
	accountsservice \
	alsa-firmware \
	alsa-utils \
	amd-ucode \
	bluez \
	bluez-hid2hci \
	bluez-plugins \
	bluez-utils \
	cifs-utils \
	diffutils \
	dmidecode \
	dosbox \
	eog \
	epiphany \
	ethtool \
	evtest \
	ffmpeg \
	file-roller \
	firejail \
	flatpak \
	fmt \
	fuse-zip \
	fuse2 \
	gamemode \
	git \
	gnome-console \
	gnome-control-center \
	gnome-disk-utility \
	gnome-keyring \
	gnome-session \
	gnome-shell \
	gnome-software \
	gnome-text-editor \
	gst-plugin-pipewire \
	haveged \
	htop \
	lib32-curl \
	lib32-fontconfig \
	lib32-freetype2 \
	lib32-gamemode \
	lib32-libgpg-error \
	lib32-libnm \
	lib32-libxinerama \
	lib32-libxcrypt-compat \
	lib32-libva \
	lib32-libva-mesa-driver \
	lib32-mesa \
	lib32-mesa-vdpau \
	lib32-openal \
	lib32-systemd \
	lib32-vulkan-icd-loader \
	lib32-vulkan-radeon \
	libcurl-gnutls \
	libidn11 \
	libretro-beetle-pce-fast \
	libretro-beetle-psx-hw \
	libretro-citra \
	libretro-desmume \
	libretro-dolphin \
	libretro-flycast \
	libretro-genesis-plus-gx \
	libretro-kronos \
	libretro-mame \
	libretro-mesen-s \
	libretro-mgba \
	libretro-mupen64plus-next \
	libretro-nestopia \
	libretro-picodrive \
	libretro-ppsspp \
	libretro-snes9x \
	libva-mesa-driver \
	libxcrypt-compat \
	libxss \
	lightdm \
	liquidctl \
	logrotate \
	lshw \
	mesa \
	mesa-demos \
	mesa-vdpau \
	nano \
	nautilus \
	networkmanager \
	nfs-utils \
	nss-mdns \
	openal \
	openssh \
	podman \
	pulsemixer \
	python \
	python-inotify-simple \
	realtime-privileges \
	retroarch \
	rsync \
	smbclient \
	sof-firmware \
	sshfs \
	steam \
	sudo \
	ttf-liberation \
	unzip \
	usb_modeswitch \
	usbutils \
	vim \
	vulkan-icd-loader \
	vulkan-radeon \
	wavpack \
	wget \
	which \
	wireplumber \
	wqy-zenhei \
	xdg-desktop-portal \
	xdg-desktop-portal-gnome \
	xdg-desktop-portal-wlr \
	xdg-user-dirs-gtk \
	xf86-video-amdgpu \
	xorg-server \
	zsh \
	zsh-completions \
"

export PACKAGE_OVERRIDES="\
	https://github.com/ChimeraOS/linux-chimeraos/releases/download/v6.3.9-chos2/linux-chimeraos-6.3.9.chos2-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/linux-chimeraos/releases/download/v6.3.9-chos2/linux-chimeraos-headers-6.3.9.chos2-1-x86_64.pkg.tar.zst \
	https://archive.archlinux.org/repos/2023/06/28/extra/os/x86_64/libretro-pcsx2-11900-2-x86_64.pkg.tar.zst \
"

# Each entry is the clone url (https://aur.archlinux.org/{AUR_PACKAGE}.git)
# Which is often the same as the package name but it can be different.
# Check on the AUR webpage if you are unsure
export AUR_PACKAGES="\
	boxtron \
	chimera \
	chimeraos-device-quirks-git \
	downgrade \
	frzr \
	gamescope-plus \
	gamescope-session-git \
	handygccs-git \
	hhfc-git \
	legendary \
	lib32-gamescope-plus \
	lib32-vkbasalt \
	libretro-dosbox-pure-git \
	libretro-opera-git \
	libretro-prosystem-git \
	libretro-stella2014-git \
	libretro-virtualjaguar-git \
	nintendo-udev \
	opengamepadui-bin \
	opengamepadui-session-git \
	pikaur \
	python-vdf \
	retroarch-autoconfig-udev-git \
	ryzenadj-git \
	steam-removable-media-git \
	vkbasalt \
	wyvern \
"

export SERVICES="\
	NetworkManager \
	avahi-daemon \
	bluetooth \
	bluetooth-workaround \
	chimera-proxy.service \
	chimera-proxy.socket \
	fstrim.timer \
	handycon \
	haveged \
	lightdm \
	sshd \
	systemd-timesyncd \
"

export USER_SERVICES="\
	chimera.service \
	gamemoded.service \
	steam-patch.service \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/SFML \
	/usr/share/doc \
	/usr/share/gtk-doc \
	/usr/share/help \
	/usr/share/libretro/autoconfig/udev/Gasia_PS_Gamepad_USB.cfg \
	/usr/share/libretro/autoconfig/udev/Sony-PlayStation3-DualShock3-Controller-Bluetooth.cfg \
	/usr/share/libretro/autoconfig/udev/Xbox_360_Wireless_Receiver_Chinese01.cfg \
	/usr/share/man \
"

postinstallhook() {
	# Add sudo permissions
	sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/dmidecode -t 11
	" > /etc/sudoers.d/steam
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-gamescope
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-lightdm
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/share/chimera/bin/power-tool
	" > /etc/sudoers.d/chimera

	# Set zsh as default shell
	chsh -s /usr/bin/zsh $USERNAME

	# disable retroarch menu in joypad configs
	find /usr/share/libretro/autoconfig -type f -name '*.cfg' | xargs -d '\n' sed -i '/input_menu_toggle_btn/d'

	# download and add racing wheel udev rules
	pushd /usr/lib/udev/rules.d
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-fanatec-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-logitech-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-thrustmaster-wheel-perms.rules
	popd

	# Remove build tools for slimmer image
	pacman --noconfirm -Rnsdd ${KERNEL_PACKAGE}-headers

	# remove dolphin standalone emulator files (only need /usr/share/dolphin-emu/sys)
	rm /usr/bin/dolphin-emu
	rm /usr/bin/dolphin-emu-nogui
	rm /usr/bin/dolphin-tool
	rm /usr/share/applications/dolphin-emu.desktop

	# clean up desktop shortcuts
	sed -i -e 's/Name=Steam (Runtime)/Name=Steam/' /usr/share/applications/steam.desktop
	find /usr/share/applications/* | \
	grep -v org.chimeraos.Gamescope.desktop | \
	grep -v org.chimeraos.app.desktop | \
	grep -v org.gnome.Console.desktop | \
	grep -v org.gnome.DiskUtility.desktop | \
	grep -v org.gnome.FileRoller.desktop | \
	grep -v org.gnome.Nautilus.desktop | \
	grep -v org.gnome.Settings.desktop | \
	grep -v org.gnome.Software.desktop | \
	grep -v org.gnome.TextEditor.desktop | \
	grep -v steam.desktop | \
	xargs -I {} sh -c "echo NoDisplay=true >> {}"

	# force -steamdeck option in desktop mode to prevent constant steam updates
	sed -i 's,Exec=/usr/bin/steam-runtime,Exec=/usr/bin/steam-runtime -steamdeck,' /usr/share/applications/steam.desktop

}
