#! /bin/bash

export VERSION="44"
export SYSTEM_DESC="kDreamOS"
export SYSTEM_NAME="kdreamos"
export USERNAME="gamer"
export SIZE="10000MB"
export ARCHIVE_DATE=$(date -d 'yesterday' +%Y/%m/%d)
export WEBSITE="https://chimeraos.org"
export DOCUMENTATION_URL="https://chimeraos.org/about"
export BUG_REPORT_URL="https://github.com/elril0000/khimeraos/issues"

export KERNEL_PACKAGE="linux-chimeraos"
export KERNEL_PACKAGE_ORIGIN="local"

export PACKAGES="\
	accountsservice \
	akonadi-calendar-tools \
	akonadiconsole \
	alsa-firmware \
	alsa-utils \
	bluez \
	bluez-hid2hci \
	bluez-plugins \
	bluez-utils \
	breeze-icons \
	cifs-utils \
	colord-kde \
	cronie \
	diffutils \
	distrobox \
	dkms \
	dmidecode \
	dosbox \
	dragon \
	ethtool \
	evtest \
	ffmpeg \
	ffmpegthumbs \
	firejail \
	flatpak \
	fmt \
	fuse-zip \
	fuse2 \
	fwupd \
	gamemode \
	git \
	gst-plugin-pipewire \
	haveged \
	htop \
	k3b \
	kaddressbook \
	kalarm \
	kalendar \
	kate \
	kcharselect \
	kdeconnect \
	kdegraphics-thumbnailers \
	kdenetwork-filesharing \
	kdepim-addons \
	kde-accessibility-meta \
	kde-system-meta \
	kdf \
	kdialog \
	keepassxc \
	kio-extras \
	kio-zeroconf \
	kgpg \
	kmail \
	knotes \
	konsole \
	kontact \
	kopete \
	korganizer \
	krfb \
	ksshaskpass \
	ktimer \
	kwalletmanager \
	kweather \
	lib32-curl \
	lib32-fontconfig \
	lib32-freetype2 \
	lib32-gamemode \
	lib32-libgpg-error \
	lib32-libnm \
	lib32-libxinerama \
	lib32-libxcrypt-compat \
	lib32-libva \
	lib32-openal \
	lib32-pipewire \
	lib32-systemd \
	lib32-vulkan-icd-loader \
	libcurl-gnutls \
	libidn11 \
	libxcrypt-compat \
	libxss \
	liquidctl \
	logrotate \
	lshw \
	nano \
	networkmanager \
	networkmanager-openvpn \
	nfs-utils \
	noise-suppression-for-voice \
	noto-fonts-emoji \
	nss-mdns \
	openal \
	openssh \
	pipewire \
	pipewire-alsa \
	pipewire-jack \
	pipewire-pulse \
	pavucontrol-qt \
	phonon-qt5-vlc \
	plasma \
	plasma-wayland-protocols \
	plasma-wayland-session \
	plasma5-applets-window-buttons \
	podman \
	print-manager \
	pulsemixer \
	python \
	python-inotify-simple \
	realtime-privileges \
	retroarch \
	rsync \
	smbclient \
	sof-firmware \
	spectacle \
	sshfs \
	steam \
	sudo \
	svgpart \
	sweeper \
	telepathy-kde-meta \
	ttf-liberation \
	ttf-meslo-nerd \
	unzip \
	usb_modeswitch \
	usbutils \
	vi \
	vim \
	vulkan-icd-loader \
	wavpack \
	wget \
	which \
	wireplumber \
	wqy-zenhei \
	xdg-desktop-portal \
	xdg-desktop-portal-kde \
	xdg-desktop-portal-wlr \
	xdg-user-dirs \
	xf86-video-amdgpu \
	xorg-server \
"

export PACKAGE_OVERRIDES="\
	https://github.com/ChimeraOS/linux-chimeraos/releases/download/v6.4.9-chos1-1/linux-chimeraos-6.4.9.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/linux-chimeraos/releases/download/v6.4.9-chos1-1/linux-chimeraos-headers-6.4.9.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.5-chos1-1/lib32-libva-mesa-driver-23.1.5.chos1-1-x86_64.pkg.tar.zst\
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.5-chos1-1/lib32-mesa-23.1.5.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.5-chos1-1/lib32-mesa-vdpau-23.1.5.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.5-chos1-1/lib32-vulkan-radeon-23.1.5.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.5-chos1-1/libva-mesa-driver-23.1.5.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.5-chos1-1/mesa-23.1.5.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.5-chos1-1/mesa-vdpau-23.1.5.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/23.1.5-chos1-1/vulkan-radeon-23.1.5.chos1-1-x86_64.pkg.tar.zst \
"

# Each entry is the clone url (https://aur.archlinux.org/{AUR_PACKAGE}.git)
# Which is often the same as the package name but it can be different.
# Check on the AUR webpage if you are unsure
export AUR_PACKAGES="\
	beautyline \
	chimera \
	chimeraos-device-quirks-git \
	downgrade \
	frzr \
	firefox-pwa \
	gamescope-plus \
	gamescope-session-git \
	legendary \
	lib32-gamescope-plus \
	lib32-vkbasalt \
	lightly-boehs-git \
	nintendo-udev \
	python-vdf \
	retroarch-autoconfig-udev-git \
	steam-removable-media-git \
	sweet-cursors-theme-git \
	vkbasalt \
	wyvern \
	yay \
	zenergy-dkms-git \
"

export SERVICES="\
	NetworkManager \
	avahi-daemon \
	bluetooth \
	bluetooth-workaround \
	chimera-proxy.service \
	chimera-proxy.socket \
	fstrim.timer \
	haveged \
	sddm \
	sshd \
	systemd-timesyncd \
"

export USER_SERVICES="\
	chimera.service \
	gamemoded.service \
	steam-patch.service \
	ssh-agent.service \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/SFML \
	/usr/share/doc \
	/usr/share/gtk-doc \
	/usr/share/help \
	/usr/share/man \
"

postinstallhook() {
	# Add sudo permissions
	sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/dmidecode -t 11
	" > /etc/sudoers.d/steam
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-gamescope
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-sddm
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/share/chimera/bin/power-tool
	" > /etc/sudoers.d/chimera

	# Set Sweet-cursors and BeautyLine as default
	sed 's/Inherits=Adwaita/Inherits=Sweet-cursors,BeautyLine,breeze/' -i /usr/share/icons/default/index.theme

	# link ksshaskpass
	ln -sv /usr/bin/ksshaskpass /usr/bin/ssh-askpass

	# download and add racing wheel udev rules
	pushd /usr/lib/udev/rules.d
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-fanatec-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-logitech-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-thrustmaster-wheel-perms.rules
	popd

	# Remove build tools for slimmer image
	rm /usr/share/libalpm/hooks/70-dkms-install.hook
	rm /usr/share/libalpm/hooks/70-dkms-upgrade.hook
	rm /usr/share/libalpm/hooks/71-dkms-remove.hook
	pacman --noconfirm -Rnsdd make gcc dkms ${KERNEL_PACKAGE}-headers

	# remove dolphin standalone emulator files (only need /usr/share/dolphin-emu/sys)
	rm /usr/bin/dolphin-emu
	rm /usr/bin/dolphin-emu-nogui
	rm /usr/bin/dolphin-tool
	rm /usr/share/applications/dolphin-emu.desktop

	# clean up desktop shortcuts
	sed -i -e 's/Name=Steam (Runtime)/Name=Steam/' /usr/share/applications/steam.desktop
	find /usr/share/applications/* | \
	grep -v org.chimeraos.Gamescope.desktop | \
	grep -v org.chimeraos.app.desktop | \
	grep -v org.keepassxc.KeePassXC.desktop | \
	grep -v breezestyleconfig.desktop | \
	grep -v kaddressbook-view.desktop | \
	grep -v kdesystemsettings.desktop | \
	grep -v org.kde.discover-flatpak.desktop | \
	grep -v org.kde.discover.desktop | \
	grep -v org.kde.dolphin.desktop | \
	grep -v org.kde.dragonplayer.desktop | \
	grep -v org.kde.kaddressbook.desktop | \
	grep -v org.kde.kalarm.desktop | \
	grep -v org.kde.kalendar.desktop | \
	grep -v org.kde.kate.desktop | \
	grep -v org.kde.kcharselect.desktop | \
	grep -v org.kde.kgpg.desktop | \
	grep -v org.kde.kmail2.desktop | \
	grep -v org.kde.knotes.desktop | \
	grep -v org.kde.konsole.desktop | \
	grep -v org.kde.kontact.desktop | \
	grep -v org.kde.kopete.desktop | \
	grep -v org.kde.korganizer.desktop | \
	grep -v org.kde.kwalletmanager5.desktop | \
	grep -v org.kde.kwikdisk.desktop | \
	grep -v org.kde.kwrite.desktop | \
	grep -v org.kde.partitionmanager.desktop | \
	grep -v org.kde.plasma-systemmonitor.desktop | \
	grep -v org.kde.plasma.cuttlefish.desktop | \
	grep -v org.kde.plasma.emojier.desktop | \
	grep -v org.kde.spectacle.desktop | \
	grep -v org.kde.sweeper.desktop | \
	grep -v org.kde.systemmonitor.desktop | \
	grep -v org.kde.yakuake.desktop | \
	grep -v pavucontrol-qt.desktop | \
	grep -v systemsettings.desktop | \
	grep -v vlc.desktop | \
	grep -v steam.desktop | \
	xargs -I {} sh -c "echo NoDisplay=true >> {}"

	# force -steamdeck option in desktop mode to prevent constant steam updates
	sed -i 's,Exec=/usr/bin/steam-runtime,Exec=/usr/bin/steam-runtime -steamdeck,' /usr/share/applications/steam.desktop
}
